model: Qwen/Qwen3-0.6B
trust_remote_code: true
model_class: llm

template: qwen3_nothink

# FSDP Config
dist_config:
  name: fsdp2
  dcp_path: null
  cp_mode: ulysses
  cp_size: 2

### data
train_dataset: data/v1_sft_demo.yaml

### training
output_dir: outputs/test_ulysses_cp
micro_batch_size: 1
cutoff_len: 2048
learning_rate: 1.0e-4
bf16: false
max_steps: 10
