model: /home/model/Qwen3.5-35B-A3B
trust_remote_code: true
model_class: llm
custom_chat_template: >-
  {% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{'<|im_start|>assistant\n'}}{% endif %}

kernel_config:
  name: auto
  include_kernels: auto

dist_config:
  name: fsdpturbo
  cp_size: 1
  ep_size: 16
  ep_dispatcher: eager
  triton_ops:
    - name: fla_chunk_gated_delta_rule
      apply_modules:
        - model.language_model.layers.{*}.linear_attn
      module_attribute: chunk_gated_delta_rule
      kwargs:
        chunk_size: 64
  param_dtype: bf16
  reduce_dtype: fp32
  ep_modules:
    - model.language_model.layers.{*}.mlp.experts
  ep_fsdp_modules:
    - model.language_model.layers.{*}.mlp
  fsdp_modules:
    model.language_model.layers.{*}.linear_attn.conv1d: {}
    model.language_model.layers.{*}.linear_attn.out_proj: {}
    model.language_model.layers.{*}.linear_attn.in_proj_qkv: {}
    model.language_model.layers.{*}.linear_attn.in_proj_z: {}
    model.language_model.layers.{*}.linear_attn.in_proj_b: {}
    model.language_model.layers.{*}.linear_attn.in_proj_a: {}
    model.language_model.layers.{*}.self_attn.q_proj: {}
    model.language_model.layers.{*}.self_attn.k_proj: {}
    model.language_model.layers.{*}.self_attn.v_proj: {}
    model.language_model.layers.{*}.self_attn.o_proj: {}
    model.language_model.layers.{*}.mlp.gate: {}
    model.language_model.layers.{*}.mlp.shared_expert.gate_proj: {}
    model.language_model.layers.{*}.mlp.shared_expert.up_proj: {}
    model.language_model.layers.{*}.mlp.shared_expert.down_proj: {}
    model.language_model.layers.{*}.mlp.shared_expert_gate: {}
    model.language_model.embed_tokens: {}
    lm_head: {}
  hook_modules:
    - model.language_model.layers.{*}

init_config:
  name: init_on_meta

### data
train_dataset: data/v1_sft_demo.yaml

### training
output_dir: /tmp/llamafactory_fsdp_plugin/smoke_qwen35_a3b_fsdpturbo_ep_fsdp2
micro_batch_size: 1
cutoff_len: 256
learning_rate: 1.0e-4
bf16: true
max_steps: 5

### sample
sample_backend: hf
max_new_tokens: 128
