model: Qwen/Qwen3.5-35B-A3B
model_class: llm
template: qwen3_5_nothink

kernel_config:
  name: auto
  include_kernels: auto

dist_config:
  name: fsdpturbo
  cp_size: 1
  ep_size: 16
  ep_dispatcher: eager
  param_dtype: bf16
  reduce_dtype: fp32
  ep_modules:
    - model.language_model.layers.{*}.mlp.experts
  ep_fsdp_modules:
    - model.language_model.layers.{*}.mlp

init_config:
  name: init_on_meta

### data
train_dataset: data/v1_sft_demo.yaml

### training
output_dir: outputs/Qwen3.5-35B-A3B/full/sft
micro_batch_size: 1
cutoff_len: 256
learning_rate: 1.0e-4
bf16: true
max_steps: 5

### sample
sample_backend: hf
max_new_tokens: 128
