### model
model_name_or_path: /data/models/Qwen3.5-35B-A3B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: alpaca_en_demo
template: qwen3
cutoff_len: 512
max_samples: 1000
overwrite_cache: true

### output
output_dir: saves/Qwen3.5-35B-A3B-lora-kt
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true

### ktransformers
use_kt: true
