### model
# model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
model_name_or_path: /lustre/fast/fast/zqiu/hf_models/Llama-3.2-1B-Instruct
adapter_name_or_path: saves/llama3-8b/oft/sft
trust_remote_code: true

### method
finetuning_type: oft

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/llama3-8b/oft/eval

### eval
batch_size: 4
