x-build-args: &build-args
  PIP_INDEX: https://pypi.org/simple

x-build: &build
  dockerfile: ./docker/docker-npu/Dockerfile
  context: ../..

x-npu-common: &npu-common
  volumes:
    - /usr/local/dcmi:/usr/local/dcmi
    - /usr/local/bin/npu-smi:/usr/local/bin/npu-smi
    - /usr/local/Ascend/driver:/usr/local/Ascend/driver
    - /etc/ascend_install.info:/etc/ascend_install.info
  ipc: host
  tty: true
  # shm_size: "16gb"  # ipc: host is set
  stdin_open: true
  command: bash
  devices:
    - /dev/davinci0
    - /dev/davinci_manager
    - /dev/devmm_svm
    - /dev/hisi_hdc
  restart: unless-stopped

services:
  llamafactory-a2-ubuntu:
    <<: *npu-common
    build:
      <<: *build
      args:
        <<: *build-args
        BASE_IMAGE: quay.io/ascend/cann:9.0.0-910b-ubuntu22.04-py3.11
    container_name: llamafactory-a2-ubuntu
    image: llamafactory:npu-a2-ubuntu
    ports:
      - "7860:7860"
      - "8000:8000"

  llamafactory-a3-ubuntu:
    <<: *npu-common
    profiles: ["a3"]
    build:
      <<: *build
      args:
        <<: *build-args
        BASE_IMAGE: quay.io/ascend/cann:9.0.0-a3-ubuntu22.04-py3.11
    container_name: llamafactory-a3-ubuntu
    image: llamafactory:npu-a3-ubuntu
    ports:
      - "7861:7860"
      - "8001:8000"

  llamafactory-a2-openeuler:
    <<: *npu-common
    profiles: ["openeuler"]
    build:
      <<: *build
      args:
        <<: *build-args
        BASE_IMAGE: quay.io/ascend/cann:9.0.0-910b-openeuler24.03-py3.11
    container_name: llamafactory-a2-openeuler
    image: llamafactory:npu-a2-openeuler
    ports:
      - "7862:7860"
      - "8002:8000"

  llamafactory-a3-openeuler:
    <<: *npu-common
    profiles: ["a3-openeuler"]
    build:
      <<: *build
      args:
        <<: *build-args
        BASE_IMAGE: quay.io/ascend/cann:9.0.0-a3-openeuler24.03-py3.11
    container_name: llamafactory-a3-openeuler
    image: llamafactory:npu-a3-openeuler
    ports:
      - "7863:7860"
      - "8003:8000"
