### model
model_name_or_path: /home/wangrui/.cache/modelscope/hub/models/Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
lora_dropout: 0.05

### dataset
dataset: mllm_reid_img2img_one2one_5k_new, mllm_reid_img2img_one2many_5k_new, mllm_reid_txt2img_one2one_2k_new, mllm_reid_txt2img_many2one_2k_new, mllm_reid_txt2img_one2many_2k_new
template: qwen2_vl
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl-7b/lora/sft_retpreid/lora16_with_progressive_16k_drop005_bs4
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
