### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true
attn: fa2
enable_liger_kernel: true
torch_compile: false

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
include_mfu: true

### dataset
dataset: tbench_traces_sharegptv1
template: qwen
mask_history: true
cutoff_len: 32768
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 8

### output
output_dir: output/qwen3_full_sft_opt_badam_layer
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.01
max_grad_norm: 1.0e-4
bf16: true
pure_bf16: false
gradient_checkpointing: true
ddp_timeout: 180000000

# Optimizer: BAdam (layer-wise) — required for ZeRO-3 and distributed
use_badam: true
badam_mode: layer
badam_switch_mode: ascending
badam_switch_interval: 50
badam_update_ratio: 0.05
badam_mask_mode: adjacent
badam_verbose: 0

### HF Hub
push_to_hub: false
