### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true
attn: fa2
enable_liger_kernel: true
torch_compile: false

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
include_mfu: true

### dataset
dataset: tbench_traces_sharegptv1
template: qwen
mask_history: true
cutoff_len: 32768
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2 #avoid issues when dev/shm is small
dataloader_prefetch_factor: 1
dataloader_persistent_workers: false
dataloader_pin_memory: false
force_file_system_sharing: true

### output
output_dir: output/qwen3_full_sft_opt_adam_mini
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.01
max_grad_norm: 1.0e-4
bf16: true
pure_bf16: false
gradient_checkpointing: true
ddp_timeout: 180000000

# Optimizer: Adam-mini
use_adam_mini: true

### HF Hub
push_to_hub: false
