# Full Fine-Tuning config for Qwen2.5-7B-Instruct on tbench_traces_sharegptv1 dataset
# Using FP8 mixed precision WITH DeepSpeed 0.17.3+ (supports FP8 via Transformer Engine)
# Based on LIMO paper configuration: https://arxiv.org/abs/2502.03387
# Enhanced with YARN RoPE scaling for extended context length (131072 tokens)
#
# Requirements:
#   - H100/H200 GPU (Hopper architecture)
#   - PyTorch >= 2.7.0
#   - Accelerate >= 1.8.0
#   - DeepSpeed >= 0.17.3 (for native FP8 support)
#   - Transformer Engine >= 2.0.0 (for FP8 backend)
#   - Log into WandB (`wandb login`) or set `report_to: none`
#   - Log into HF: `huggingface-cli login`
#
# Installation:
#   pip install -e '.[deepspeed,fp8-te]'  # For DeepSpeed + Transformer Engine FP8
#   # OR manually: pip install 'deepspeed>=0.17.3' 'transformer-engine[pytorch]>=2.0.0'
#
# Usage:
#   llamafactory-cli train qwen2_5_full_sft_fp8_deepspeed.yaml

### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
trust_remote_code: true
rope_scaling:
  rope_type: yarn
  factor: 4.0
  original_max_position_embeddings: 32768
attn: fa2
enable_liger_kernel: true

### method
stage: sft
do_train: true
finetuning_type: full  # Full fine-tuning (not LoRA)
deepspeed: examples/deepspeed/ds_z3_fp8_config.json  # DeepSpeed ZeRO-3 config with FP8

### dataset
dataset: tbench_traces_sharegptv1  # You'll need to add this to data/dataset_info.json
template: qwen  # Qwen2.5 template
cutoff_len: 131072  # Match model_max_length
max_samples: null  # Use full dataset
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 2

### FP8 Configuration - DeepSpeed 0.17.3+ with Transformer Engine
fp8: true                                   # Enable FP8 mixed precision
fp8_backend: te                             # Use Transformer Engine backend (te, msamp, auto)
fp8_enable_fsdp_float8_all_gather: true     # Enable FSDP float8 optimizations

### Mixed Precision (FP8 will override this)
bf16: false                                 # Disabled when using FP8
fp16: false                                 # Disabled when using FP8

### output
output_dir: output/qwen2_5_full_sft_fp8_deepspeed
logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: true  # Save only model for DeepSpeed compatibility
report_to: wandb  # Set to 'none' to disable WandB

### train
per_device_train_batch_size: 1              # Per device batch size with DeepSpeed
gradient_accumulation_steps: 4              # Gradient accumulation steps
learning_rate: 2.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.03
max_grad_norm: 1.0e-3                       # Gradient clipping
gradient_checkpointing: true                # Important for memory efficiency
ddp_timeout: 180000000                      # 3 hours timeout for large model loading

### Performance Optimizations
dataloader_pin_memory: false                # Reduce memory usage
remove_unused_columns: false                # Keep unused columns for compatibility

### DeepSpeed Notes:
# - DeepSpeed 0.17.3+ includes native FP8 support via Transformer Engine integration
# - FP8 with DeepSpeed ZeRO-3 should provide significant memory savings
# - Gradient accumulation and clipping are handled by DeepSpeed config
# - The fp8_backend='te' uses NVIDIA Transformer Engine for optimal H100 performance
