name: "\U0001F680 Feature request"
description: Submit a request for a new feature
labels: ["enhancement", "pending"]
body:
  - type: markdown
    attributes:
      value: |
        Please do not create issues that are not related to new features under this category.
        请勿在此分类下创建和新特性无关的 issues。

  - type: checkboxes
    id: reminder
    attributes:
      label: Reminder
      description: |
        Please ensure you have read the above rules carefully and searched the existing issues.
        请确保您已经认真阅读了上述规则并且搜索过现有的 issues。

      options:
        - label: I have read the above rules and searched the existing issues.
          required: true

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature proposal.
        请详细描述您希望加入的新功能特性。

  - type: textarea
    id: contribution
    validations:
      required: false
    attributes:
      label: Pull Request
      description: |
        Have you already created the relevant PR and submitted the code?
        您是否已经创建了相关 PR 并提交了代码？
