# Full Fine-Tuning config for Qwen2.5-7B-Instruct on tbench_traces_sharegptv1 dataset
# Enhanced with YARN RoPE scaling for extended context length (131072 tokens)
#
# Requirements:
#   - Log into WandB (`wandb login`) or set `report_to: none`
#   - Log into HF: `huggingface-cli login`
#

### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
trust_remote_code: true
rope_scaling: linear
attn: fa2
enable_liger_kernel: true

### method
stage: sft
do_train: true
finetuning_type: full  # Full fine-tuning (not LoRA)
# Note: No deepspeed config - using FSDP instead via accelerate launch

### dataset
dataset: tbench_traces_sharegptv1  # You'll need to add this to data/dataset_info.json
template: qwen  # Qwen2.5 template
mask_history: true
cutoff_len: 32768  # Match model_max_length
max_samples: null  # Use full dataset
overwrite_cache: true
preprocessing_num_workers: 16  # Match LIMO preprocessing workers
dataloader_num_workers: 2 #avoid issues when dev/shm is small
dataloader_prefetch_factor: 1
dataloader_persistent_workers: false
dataloader_pin_memory: false
force_file_system_sharing: true
group_by_length: true

### output
output_dir: output/qwen2_5_full_sft_fsdp_offload
logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: false  # Incompatible with FSDPv2
report_to: wandb  # Set to 'none' to disable WandB

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.03
max_grad_norm: 1.0e-3  # Note: LLaMA-Factory uses max_grad_norm instead of max_grad_norm
bf16: true
pure_bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000

### optimizations
# torch_compile: true
# torch_compile_backend: eager
# optim: paged_adamw_8bit incompatible with FSDP
