### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true
attn: fa2
enable_liger_kernel: true
torch_compile: false
torch_compile_backend: inductor
optim: paged_adamw_8bit

### method
stage: sft
do_train: true
finetuning_type: full  # Full fine-tuning (not LoRA)
# Enable MFU reporting (uses HF Trainer total_flos)
include_mfu: true

### dataset
dataset: tbench_traces_sharegptv1
template: qwen  # Qwen2.5 template
mask_history: true
cutoff_len: 32768
max_samples: null  # Use full dataset
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2 #avoid issues when dev/shm is small
dataloader_prefetch_factor: 1
dataloader_persistent_workers: false
dataloader_pin_memory: false

### output
output_dir: output/qwen3_full_sft_fsdp
logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: false #FSDP incompatibility
report_to: wandb  # Set to 'none' to disable WandB

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.01
max_grad_norm: 1.0e-3
bf16: true
pure_bf16: false
gradient_checkpointing: true
ddp_timeout: 180000000
