### model
model_name_or_path: Qwen/Qwen2-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z1_config_gaudi.json

### dataset
dataset: alpaca_en
template: qwen
cutoff_len: 8192
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 1

### output
output_dir: saves/qwen2-7b-instruct/full/sft/ds1
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_strategy: "no"

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 15
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
use_habana: true
use_lazy_mode: true
gaudi_config_name: Habana/qwen
compute_accuracy: true
context_parallel_size: 1
throughput_warmup_steps: 15
gradient_checkpointing: true
dataset_concatenation: true
use_flash_attention: true
flash_attention_recompute: true
flash_attention_causal_mask: true
attn_softmax_bf16: true
pipelining_fwd_bwd: true

### eval
# val_size: 0.04
# per_device_eval_batch_size: 1
# #eval_strategy: epoch
# eval_steps: 500
# eval_delay: 3