### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true
attn: fa2
enable_liger_kernel: true
torch_compile: false
rope_scaling: linear

### method
stage: sft
do_train: true
finetuning_type: full  # Full fine-tuning (not LoRA)
deepspeed: examples/deepspeed/ds_z3_partial_offload_config.json
# Enable MFU reporting (uses HF Trainer total_flos)
include_mfu: true

### dataset
dataset: tbench_traces_sharegptv1
template: qwen  # Qwen2.5 template
mask_history: true
cutoff_len: 122880  # Match model_max_length
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2 #avoid issues when dev/shm is small
dataloader_prefetch_factor: 1
dataloader_persistent_workers: false
dataloader_pin_memory: false
force_file_system_sharing: true
group_by_length: true

### output
output_dir: output/qwen3_full_sft_deepspeed
logging_steps: 5
save_strategy: "no"
save_total_limit: 1
load_best_model_at_end: false
evaluation_strategy: "no"   # optional
logging_strategy: "steps"   # keep as you like
plot_loss: true
overwrite_output_dir: true
save_only_model: true  # Save only model for DeepSpeed compatibility
report_to: wandb  # Set to 'none' to disable WandB

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.01
max_grad_norm: 1.0e-4
bf16: true
pure_bf16: false
gradient_checkpointing: true
ddp_timeout: 180000000

### Hugging Face Hub push (Trainer-based)
# Enable automatic pushing from HF Trainer. Commonly, rank-0 pushes at the end.
push_to_hub: true
hub_model_id: penfever/qwen3_full_sft_deepspeed
hub_strategy: end
hub_private_repo: true
