### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true
rope_scaling:
  rope_type: yarn
  factor: 2.0
  original_max_position_embeddings: 32768
attn: kernels-community/vllm-flash-attn3
enable_liger_kernel: true

### method
stage: sft
do_train: true
finetuning_type: full  # Full fine-tuning (not LoRA)
deepspeed: examples/deepspeed/ds_z3_partial_offload_config.json
# Enable MFU reporting (uses HF Trainer total_flos)
include_mfu: true
# Optional tuning knobs for future DeepSpeed sampling
mfu_profile_every: 25
mfu_warmup_steps: 5

### dataset
dataset: tbench_traces_sharegptv1
template: qwen
cutoff_len: 65536
max_samples: null  # Use full dataset
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: output/qwen3_8b_tbench_traces_sharegptv1_yarn_ds
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: true  # Save only model for DeepSpeed compatibility
report_to: wandb  # Set to 'none' to disable WandB

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.03
max_grad_norm: 1.0e-3
bf16: true
pure_bf16: false
gradient_checkpointing: true
ddp_timeout: 180000000
