### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true
attn: fa2
enable_liger_kernel: true
torch_compile: false

### method
stage: sft
do_train: true
finetuning_type: full  # Full fine-tuning (not LoRA)
deepspeed: examples/deepspeed/ds_z3_config.json
# Enable MFU reporting (uses HF Trainer total_flos)
include_mfu: true

### dataset
dataset: tbench_traces_sharegptv1
template: qwen  # Qwen2.5 template
mask_history: true
cutoff_len: 32768
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: output/qwen3_full_sft_deepspeed_online
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: true  # Save only model for DeepSpeed compatibility
report_to: wandb  # Set to 'none' to disable WandB

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.01
max_grad_norm: 1.0e-4
bf16: true
pure_bf16: false
gradient_checkpointing: true
ddp_timeout: 180000000

### Hugging Face Hub push (Trainer-based)
# Enable automatic pushing from HF Trainer. Commonly, rank-0 pushes at the end.
push_to_hub: true
hub_model_id: penfever/qwen3_full_sft_deepspeed_online
hub_strategy: end
hub_private_repo: true
