accelerate launch --config_file accelerate_config.yaml  src/train_bash.py \
    --stage sft \
    --model_name_or_path /home/mediatek/models/Llama-2-13b-hf \
    --do_train \
    --dataset alpaca_gpt4_en \
    --finetuning_type lora \
    --output_dir ./outputs/sft_test \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --fp16
