# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.02
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 1

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  COOP:
    CTX_INIT: "a photo of a"
optuna_cfg:
  n_trials: 30
  n_warmup_steps: 15
  opt_params: [{'OPTIM.LR': {'range':[1e-9, 1e-8], 'log': false}, 'DATALOADER.TRAIN_X.BATCH_SIZE': {'range':[1,3], 'log': false}}]
  sampler:
    name: "TPESampler"
