# Example configuration for Quantization Aware Training (QAT) with LLaMA-3
# Trains model with fake quantization, output can be quantized for deployment

### Model
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
trust_remote_code: true

### Method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05

### Dataset
dataset: alpaca_en
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### Output
output_dir: ./saves/llama3-3b-qat-sft
logging_steps: 10
save_steps: 500
save_total_limit: 2
plot_loss: true
overwrite_output_dir: true

### Train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### QAT Configuration
enable_qat: true                        # Enable Quantization Aware Training
qat_activation_dtype: int8              # Quantize activations to int8 (optional)
qat_weight_dtype: int8                  # Quantize weights to int8  
qat_group_size: 32                      # Quantization group size
qat_quantize_embedding: true            # Quantize embedding layers
fake_quant_after_n_steps: 100           # Enable fake quantization after 100 steps

### Advanced Options
use_liger_kernel: true                  # Use Liger kernels for additional optimization
flash_attn: auto                        # Use FlashAttention

### Eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 250