name: Docker

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/*.yml"

env:
  REGISTRY: docker.io
  IMAGE_NAME: llamafactory

jobs:
  docker-build-and-push:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/docker-cuda/Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/llamafactory:latest
