name: publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: Upload release to PyPI

    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/p/llamafactory

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: "3.11"
          github-token: ${{ github.token }}

      - name: Build package
        run: |
          make build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1
